platform :ios, '14.0'

target 'PersonalDictionaryDev' do
  use_frameworks!

  pod 'SwiftLint'

  pod 'CoreModule',
    :path => '../../AppModules/CoreModule'
  pod 'PersonalDictionary',
    :path => '../../AppModules/PersonalDictionary'
  pod 'TodoList',
    :path => '../../AppModules/TodoList'

  target 'PersonalDictionaryDevTests' do
    inherit! :search_paths

    pod 'RxBlocking', '5.1'

  end

  post_install do |installer|
   installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
   end
  end

end
